### PR TITLE
changes to the README

### PR DESCRIPTION
**Pull request by gusalbukrk**
This is my first comment.

### CODE REVIEW

**Comment by gusalbukrk** [comment]
Is it good?

**Comment by gustavoalbuquerquebr** [comment]
It's great. Thanks!

**Comment by gusalbukrk** [comment]
> Is it good?

Yes

**Review by gustavoalbuquerquebr — APPROVED** [review]

**Comment by gustavoalbuquerquebr** [comment]
merging pull request

**Pull request merged**
